### ISSUE TITLE
[Updated] Trying how /login works - AuthenticationHeaderFilter

### ISSUE THREAD

**Issue by hazartilirot** [simplyi/SpringCloudAPIGateway#2]
In case you've reached the lesson. There would be a problem to run the **SpringCloudAPIGateway**

If you have followed up until now and made sure that there is no mistake on your side the problem you encounter is at the **00:30** of **Configure API Gateway route to /login**

He uses a filter which doesn't exist **AuthenticationHeaderFilter**. Delete the line or add the class

https://github.com/simplyi/SpringCloudAPIGateway/blob/main/src/main/java/com/appsdeveloperblog/photoapp/api/gateway/AuthorizationHeaderFilter.java

Mind the **PATH**!!!!!! to the class.

However, as a first step to solve the problem I suggest that you delete the line

_spring.cloud.gateway.routes[0].filters[2]=AuthorizationHeaderFilter_

If it works - than you know the exact hindrance. Then create the class, copy the code and return the code's line .

Now, I use **application.yml** file therefore if you need my help feel free to copy the text:

```
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-status-check
          uri: lb://users-ws
          predicates:
            - Path=/users/status/check
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
           - RemoveRequestHeader=Cookie
           - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
           - AuthorizationHeaderFilter
        - id: users-ws
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/users
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
        - id: users-ws-2h-console
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/h2-console
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
        - id: users-ws-2h-login
          uri: lb://users-ws
          predicates:
            - Path=/users-ws/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-ws/(?<segment>.*), /$\{segment}
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

```
